### PR TITLE
Added performance management component

### PR DESCRIPTION
**Pull request by Cici919**
Added performanceManagement  in the Components folder, and add the required code piece in the dashboard.js, And has run the code on local test work then push this request.

### CODE REVIEW

**Comment by greeshiee** [comment]
i merged the code into a different branch, but is the idea to click the link? we currently don't have your backend integrated, so clicking on it redirects to localhost:5000 - which im assuming is where your server runs

**Comment by Cici919** [comment]
Yes click the link should link to the visualization of the data

**Comment by Cici919** [comment]
Also I have a question, how my other team members can login in the auth0
since for our team project I used my gmail login in ! So will they can
access the Auth0 by their own gmail account?

**Comment by Cici919** [comment]
For our integration with your team, right now you only have our front end
code, if finally they make your team as the whole class project repository
we need upload our backend code into your project too. Then from the menu
bar click Performance manager will lead to our frontend, then from there
click dashboard will lead to an external link to our dashboard
visualization! That is how the flow of work works

**Comment by Cici919** [comment]
Sorry to send you so much email, also right now you only have our frontend
code, base on today’s class meeting seems they will make your guys
repository to the gene tone for the whole class. Therefore I think we and
also all the team need give our whole code to your team!
Is that correct?

**Pull request merged**
